"""add Admin.cloud_keys relationship

Revision ID: 23624dd4535e
Revises: 488056479ffb
Create Date: 2025-05-02 19:37:31.148533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23624dd4535e'
down_revision: Union[str, None] = '488056479ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.add_column('activation_keys', sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('activation_keys', 'redeemed_device_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('activation_keys', 'allowed_device_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.add_column('cloud_keys', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_cloud_keys_id'), 'cloud_keys', ['id'], unique=False)
    op.create_index(op.f('ix_cloud_keys_key'), 'cloud_keys', ['key'], unique=True)
    op.create_foreign_key(None, 'cloud_keys', 'admins', ['created_by'], ['id'], ondelete='CASCADE')
    op.alter_column('devices', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('devices_id_seq'::regclass)"))
    op.drop_index('ix_devices_id', table_name='devices')
    op.alter_column('dosing_operations', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('dosing_profiles', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('payment_orders', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('sensor_readings', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('subscriptions', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'device_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('sensor_readings', 'device_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payment_orders', 'device_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('dosing_profiles', 'device_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('dosing_operations', 'device_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index('ix_devices_id', 'devices', ['id'], unique=False)
    op.alter_column('devices', 'id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('devices_id_seq'::regclass)"))
    op.drop_constraint(None, 'cloud_keys', type_='foreignkey')
    op.drop_index(op.f('ix_cloud_keys_key'), table_name='cloud_keys')
    op.drop_index(op.f('ix_cloud_keys_id'), table_name='cloud_keys')
    op.drop_column('cloud_keys', 'created_by')
    op.alter_column('activation_keys', 'allowed_device_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('activation_keys', 'redeemed_device_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('activation_keys', 'redeemed_at')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
